# Build settings for Netlify deployment
[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to backend API endpoints to external service
[[redirects]]
  from = "/api/*"
  to = "https://micro-blog-espe-backend.herokuapp.com/api/:splat"
  status = 200
  force = true

# SPA redirect - all routes should serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
