# Build settings for Netlify deployment
[build]
  base = "."
  publish = "."
  command = "echo 'Static site deployment - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA redirect - all routes should serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
